### ISSUE TITLE
Refactor CLI to parametize entire framework

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#111]
- [x] Migrate getters in Configuration.java to JCommander class
- [x] Implement CLI using JCommander in Configuration.java
- [x] Add defaults
- [x] Test CLI
- [x] Make everything configurable
- [x] Add invalid parameter tests
- [x] Implement validators

Individual CLI parameter tasks (sanity check):
- [x] Framework name
- [x] Executor image
- [x] Executor Disk/RAM/CPU size
- [x] Health check ping and timeout settings

**Comment by philwinder** [comment]
- [ ] Migrate getters in Configuration.java to JCommander class
- [ ] Implement CLI using JCommander in Configuration.java
- [ ] Add defaults
- [ ] Test CLI
- [ ] Add invalid parameter tests
- [ ] Implement validators

**Comment by philwinder** [comment]
Fixed in #235
