### ISSUE TITLE
Provide docker configuration image

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#116]
As a user, I want to be able to provide my own elasticsearch settings.
I understand that some of these settings may be overwritten by the framework. For example: node.name, node.master, cluster.name, etc.

A primary fix for this was submitted in #242. However is very fragile.
Recommend allowing user to provide a data image for configuration.
Recommend allowing user to specify any path.

**Comment by philwinder** [comment]
Proposal:
We use a very lightweight webserver to host the elasticsearch.yml, logging.yml and any Mesos Elasticsearch settings we desire. When they launch the Elasticsearch process, the executors will connect to the webserver and import the settings over HTTP.

The scheduler is responsible for the lifecycle of the webserver. The scheduler will pass in URLs for the settings in a format that seems best. (ENV var? TaskInfo?)

Inside the scheduler, we will download and instantiate the docker image and obtain the IP address (using the mini-meos AbstractContainer?). If no image is specified it will download a standard image.

Inside the executor we will use the ES java API has a method that is capable of downloading ES settings files from a URL. (ImmutableSettings.settingsBuilder().loadFromUrl()). Custom loaders may be necessary for any ES-Mesos specific settings.

The user will simply specify the name of the docker image that contains these settings so that the user is able to override the docker image with their own settings files.

**Comment by philwinder** [comment]
The above proposal is a little complicated at the moment. For this version I will:
One extra CLI parameter called —elasticsearch-settings=“/etc/elasticsearch/config/elasticsearch.yml”. (It will use the default settings if none provided)
Phase 1. This file must be on every slave in the cluster.
Phase 2. Host the file from the scheduler. The settings file only needs to be on the scheduler slave.
Future: The above proposal, settings docker image.

**Comment by frankscholten** [comment]
Sounds good. Let's create another issue for the simpler version and move this one to the backlog

**Comment by philwinder** [comment]
Partially implemented in #243. No desire to make it more complex at this time.
