### ISSUE TITLE
Use built executor docker image in docker-compose setup

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#125]
Currently, the docker-compose scripts will only obtain the executor docker images from docker hub. The developer is not able to use his built images.

Hence, the user should be able to provide their own docker images.

This can be completed by editing the executor docker image to extend the dind image. Then we can simply pass that image into docker-compose, like we do for the scheduler.

**Comment by frankscholten** [comment]
The docker-compose setup is designed to share Docker images between inner and outer Docker.

See https://github.com/mesos/elasticsearch/blob/master/system-test/src/test/resources/mesos-es/slave.yml It contains the volumes necessary to share images.

If the inner Docker uses a different storage driver than the outer Docker then they cannot see eachother's images. It seems you are running into this issue.

**Comment by frankscholten** [comment]
System test works on Linux. Looking now at running it with Docker machine.

**Comment by frankscholten** [comment]
We are working on docker-in-docker without volumes. We use docker save and load.

See https://github.com/mesos/elasticsearch/pull/137

The only remaining issue is fixing node discovery
