### ISSUE TITLE
Possible to deploy onto existing mesos cluster without hdfs?

### ISSUE THREAD

**Issue by F21** [mesos/elasticsearch#146]
I am currently building a small test cluster to play with mesos. As the cluster runs on virtual machines, mesosphere/hdfs is too heavy to deploy. Is it possible to get this deployed directly on mesos without the hdfs requirement?

**Comment by frankscholten** [comment]
HDFS is not a requirement of the framework

**Comment by F21** [comment]
The instructions for deploying to mesos in the README as well as the following scripts require HDFS:

`deploy-cloud-mesos.sh`
`deploy-executor.sh`
`deploy-scheduler.sh`

**Comment by frankscholten** [comment]
Yes, these are out of date. We will update them https://github.com/mesos/elasticsearch/issues/133
