### ISSUE TITLE
Scheduler: Java out of memory

### ISSUE THREAD

**Issue by tymofii-polekhin** [mesos/elasticsearch#148]
Hello,

i've been playing with ES framework a bit and found out that scheduler dies after some time, and then marathon restarts is again with 3 new executors. This continues till all cluster resources are gone.

After a bit of log investiogation i've managed to find the problem:
The scheduler jar is launched without any java memory options, and when it exceedes the deafult 256m of ram mesos kills it. Marathon restarts the scheduler and it goes again...

I've added -Xms -Xmx options to the scheduler container `ENTRYPOINT`

Current framework uptime is 4 days.

**Comment by frankscholten** [comment]
Thanks for reporting this @tymofii-polekhin Please add a PR so we can merge your changes

**Comment by philwinder** [comment]
This could be a little tricky. The user is able to request how much RAM to give the scheduler/executors. The heap size should be linked to this value. However AFAIK you can't change the heap size at runtime. It must be upon startup.

**Comment by philwinder** [comment]
Tested options above, they are working on DCOS cluster (20 hrs no restarts). Need to add to documentation and alter executor heap space management. See #167
