### ISSUE TITLE
Setting the web ui port via "-m" does not work.

### ISSUE THREAD

**Issue by F21** [mesos/elasticsearch#149]
I am running the scheduler using the mesos/elasticsearch-scheduler docker image from docker hub (https://registry.hub.docker.com/u/mesos/elasticsearch-scheduler/).

If I do not set a port for the web ui, it works fine:
```
 sudo docker run -it -p 9876:8080 mesos/elasticsearch-scheduler -n 1 -zk zk://master .mesos:2181/mesos
```

However, if I try to set the port using `-m`, I am unable to access the web ui:

```
 sudo docker run -it -p 9876:9876 mesos/elasticsearch-scheduler -m 9876 -n 1 -zk zk://master .mesos:2181/mesos
```

**Comment by frankscholten** [comment]
Fixed in https://github.com/mesos/elasticsearch/pull/160
