### ISSUE TITLE
Configure overall cluster disk size

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#155]
As a user I want to configure the overal disk size of the cluster.

Internally the framework will compute the minimum disk size per offer by taking the overal disk size and divide it by the number of nodes (-n)

```
dcos install  elasticsearch  —size=2TB 
```

**Comment by philwinder** [comment]
Duplicate of #111

**Comment by philwinder** [comment]
Fixed in pull/235

**Comment by philwinder** [comment]
#235
