### ISSUE TITLE
Create vagrant configuration for the project

### ISSUE THREAD

**Issue by mrmrcoleman** [mesos/elasticsearch#16]
I prefer to work in Vagrant wherever possible so as to avoid polluting my laptop. I'm working on a centos7 box for myself right now anyway to solve this problem.

If there is demand for this, please let me know and also state your preferred distribution. I have no particular preference for centos.

**Comment by mrmrcoleman** [comment]
@mwl +1 over Slack for Centos7 so I'm proceeding there.

**Comment by mwl** [comment]
The more you can work offline in a reproducible environment, the happier I am.

**Comment by mrmrcoleman** [comment]
Cool. I pushed the first version to the executor branch on the CS repo. Can you try it out and let me know if it works for you?

**Comment by mrmrcoleman** [comment]
Works for me on:

Vagrant 1.6.5
VirtualBox 4.3.20

**Comment by mrmrcoleman** [comment]
Re-opening as we need to persist the gradle cache.

**Comment by mrmrcoleman** [comment]
Still to do:
- [ ] Persist GRADLE_BUILD_HOME
- [ ] Persist JAVA_HOME
- [ ] Check if SELinux stays off between restarts

**Comment by mrmrcoleman** [comment]
Running builds as root is no problem for now so closing.
