### ISSUE TITLE
Executor task management

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#166]
Add task management. Should be able to:
* Restart if task fails
* Use checkpoint
* Monitor state of tasks (via healthcheck?)

As reported in #164 by @F21

**Comment by F21** [comment]
It should also be able to regain controlled of orphaned tasks. I have seen cases where I set the number of tasks to 1 and the scheduler gets terminated for whatever reason. When the scheduler comes back up, it starts another task, so we end up with 2 tasks instead of 1.

**Comment by frankscholten** [comment]
See https://github.com/mesos/elasticsearch/issues/177

**Comment by philwinder** [comment]
* Mesos doesn’t send executor status messages properly. https://issues.apache.org/jira/browse/MESOS-313
* Can’t use the inbuilt healthcheck mechanism yet either. HTTP not implemented.
https://issues.apache.org/jira/browse/MESOS-2533

So this is my proposal:
1. Upon start, scheduler checks zookeeper to check for executor state
2. Periodically, scheduler sends custom healthcheck request message as a custom framework message.
3. Executor receives message and responds with custom framework message.
4a. Scheduler updates zookeeper executor state.
4b. If executor doesn't respond within timeout, assume dead. Clears zookeeper state for that executor.

Other changes:
1. Scheduler will populate task list by querying zookeeper. No state managed in scheduler.

Assumptions:
This assumes that the scheduler is able to re-register with the same framework ID.

**Comment by philwinder** [comment]
Fixed in https://github.com/mesos/elasticsearch/pull/207
