### ISSUE TITLE
Move ES ZK plugin into group control

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#172]
The ES ZK plugin is currently hosted at:
https://github.com/trifork-leeds/elasticsearch-zookeeper
It should be placed under group control.

**Comment by frankscholten** [comment]
https://github.com/ContainerSolutions/elasticsearch-zookeeper

**Comment by frankscholten** [comment]
* Update Jitpack configuration so mesos-elasticseach uses this repository
* Update CI

**Comment by mwl** [comment]
Repo is now living at https://github.com/ContainerSolutions/elasticsearch-zookeeper

**Comment by mwl** [comment]
Task list

- [ ] Clone repo into ContainerSolutions org
- [ ] Bump ElasticSearch version to 1.7 in module, elastic ContainerSolutions/elasticsearch-zookeeper#2
- [ ] Change Executor dependency to elasticsearch-zookeeper:1.7.0
