### ISSUE TITLE
Docker tests slowly eat HDD space

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#173]
After each test (on docker-machine), our tests or docker to not clean the docker daemon directory correctly. The hard drive is filled at approximately 1GB per run. Eventually the VM hard drive becomes full and the tests fail.

Need to investigate and verify.

**Comment by frankscholten** [comment]
I experienced the same issue. My /var/lib/docker/volumes directory was full of volumes.

Let's start with a clean folder and see which volumes are created after a test run.

It could also be this line in https://github.com/ContainerSolutions/mesos-local/blob/master/Dockerfile#L55 in the mesos-local Dockerfile

**Comment by frankscholten** [comment]
https://github.com/ContainerSolutions/mini-mesos/issues/34

**Comment by frankscholten** [comment]
We have removed registry volume in mini-mesos https://github.com/ContainerSolutions/mini-mesos/issues/34 so this should be fixed
