### ISSUE TITLE
./gradlew :scheduler:buildDockerImage results in invalid scheduler build

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#190]
I think there is an issue when you run `./gradlew :scheduler:buildDockerImage`, results in an invalid build. I get "missing bean" exceptions.

It works if you do a build before the docker image build:
`./gradlew build :scheduler:buildDockerImage`

**Comment by mwl** [comment]
Steps to reproduce:

Make sure you have a clean workspace

```bash
./gradlew :scheduler:buildDockerImage
./gradlew main
```

**Comment by mwl** [comment]
Looks like `:buildDockerImage` is depending on `:scheduler:taskCopyFilesForDocker` depending on `:scheduler:copyJar` depending on `:jar`.
To make a correct spring boot fat jar you need to execute `:bootRepackage`.
