### ISSUE TITLE
After reconcillication, GUI does not show true state of cluster

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#206]
The introduced cluster management code does not update the GUI Task data structure, because some fields are not available when reconciling. E.g. the slave IP address is not available.

We need to consider removing items that are not available to the scheduler at reconcillication time. E.g. the IP address of the slave.

If they are important then we need to implement custom code to pass those details from the executors.
- Scheduler death: GUI will show zero tasks
- Executor death: GUI will show n + 1 tasks, since the task is not removed from the task list.

**Comment by philwinder** [comment]
Could initialize com.sonian.elasticsearch.zookeeper.discovery.ZooKeeperClusterState in the scheduler to read the ES state written by ES? Then we should be able to parse the hostname and ports from Elasticsearch's DiscoveryNode.

This is probably the best idea, because the data is already there and required for the ES discovery mechanism. However, this does couple the scheduler code to ES/ES-Zookeeper. Should seperate the code out from the scheduler as much as possible.

**Comment by a-nldisr** [comment]
Is my assumption correct that this is related to when an executor fails, this failed executor is still listed in the dropdown list on the GUI?

**Comment by frankscholten** [comment]
@a-nldisr Yes

**Comment by a-nldisr** [comment]
thnx

**Comment by philwinder** [comment]
Fixed in #302
