### ISSUE TITLE
DCOS requirement: Support mesos framework role

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#221]
Should we also implement resource allocation for roles?

See:
https://open.mesosphere.com/reference/mesos-master/
https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L155

Implementation in marathon:
https://github.com/mesosphere/marathon/blob/c7624e0c3778da02919e743e8b9eda7248acd1a1/src/main/scala/mesosphere/marathon/MarathonSchedulerDriver.scala#L27
https://github.com/mesosphere/marathon/blob/c7624e0c3778da02919e743e8b9eda7248acd1a1/src/main/scala/mesosphere/marathon/MarathonConf.scala#L84

Link:
https://github.com/mesosphere/universe/pull/193

**Comment by Aerlinger** [comment]
This is to set the role for the task executors, correct? I believe this setting is used with the "acceptedResourceRoles" parameter in marathon https://mesosphere.github.io/marathon/docs/rest-api.html#acceptedresourceroles-v0-9-0 which is also necessary to have the elasticsearch API run publicly: https://docs.mesosphere.com/getting-started/dcosarchitecture/.

**Comment by jhftrifork** [comment]
@philwinder I guess your link to the mesos proto definitions originally pointed to this line: https://github.com/apache/mesos/blob/50344bcaea8b462c1bb096ba46b1d1401b26ba3a/include/mesos/mesos.proto#L249

```
/**
 * Describes a framework.
 */
message FrameworkInfo {
  [...]

  // Used to group frameworks for allocation decisions, depending on
  // the allocation policy being used.
  optional string role = 6 [default = "*"];

  [...]
}
```

**Comment by jhftrifork** [comment]
Should just be a case of passing a "role" string when creating a `Protos.FrameworkInfo`.

We do this in our `FrameworkInfoFactory`.

By analogy with other properties, the string should come from an instance of our `Configuration` class.

I think we can essentially copy the pattern for `configuration.getFrameworkName()`, `configuration.getFailoverTimeout()`, etc.

**Comment by jhftrifork** [comment]
As mentioned by @mwl in https://github.com/mesos/elasticsearch/issues/215 , this is required for DCOS certification; we should have comments to this effect in the source.

**Comment by jhftrifork** [comment]
Anyone: which DCOS requirement number is this?

**Comment by mwl** [comment]
@kensipe, @philwinder: Can you please help @jhftrifork here?
