### ISSUE TITLE
Upgrade to Mesos 0.23 to support persistent volumes

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#228]

**Comment by frankscholten** [comment]
Persistent volumes depends on reservation and authorization but authorization support in Elasticsearch is blocked #218

**Comment by a-nldisr** [comment]
Hi, 

Version 0.24.0 is released, are there plans to skip 0.23.0 and go for 0.24.0 instead?

**Comment by philwinder** [comment]
Duplicate of #338

**Comment by sarwarbhuiyan** [comment]
Did you mean #306
