### ISSUE TITLE
Allow to use simple elasticsearch jar instead of docker image

### ISSUE THREAD

**Issue by kamaradclimber** [mesos/elasticsearch#233]
In our organization, we don't have docker on our production mesos cluster. It would nice to allow using bare elasticsearch jar instead of enforcing docker.

I understand that it would increase complexity of the executor a bit.

**Comment by frankscholten** [comment]
@kamaradclimber Thanks for your feedback on the project! We saw the issues you added.

We might support this if there is a lot of demand for it but probably not any time soon. Docker gives us a proper mechanism for configuration management and distribution of framework code out of the box.
When supporting jars we have to build these mechanisms ourselves. 

Issue https://github.com/mesos/elasticsearch/issues/71 will be supported though in the upcoming 0.3 release.

**Comment by philwinder** [comment]
Fixed in #355
