### ISSUE TITLE
Cluster deployment via Terraform

### ISSUE THREAD

**Issue by mrmrcoleman** [mesos/elasticsearch#24]

**Comment by frankscholten** [comment]
To deploy via Terraform https://github.com/ContainerSolutions/terraform-mesos should support HDFS. This means installing a Hadoop NameNode on the master and DataNodes on all the slaves.

**Comment by frankscholten** [comment]
We will replace HDFS with a small webserver running on the scheduler so we don't need HDFS to distribute executors.
