### ISSUE TITLE
Unable to launch docker container 

### ISSUE THREAD

**Issue by F21** [mesos/elasticsearch#276]
I am trying to launch the executor container via marathon 0.10.1 and mesos 0.23:

```json
{
  "id": "elasticsearch-mesos-scheduler",
  "container": {
    "docker": {
      "image": "mesos/elasticsearch-scheduler",
      "network": "HOST"
    }
  },
  "args": ["--zookeeperMesosUrl", "zk://master.mesos:2181/mesos"],
  "cpus": 0.2,
  "mem": 512.0,
  "env": {
    "JAVA_OPTS": "-Xms128m -Xmx256m"
  },
  "instances": 1
}
```

Unfortunately, the deployment fails. There is no output in `stdout`, but in `stderr`, I see:
```
No such file or directory
```

The elasticsearch-schdeuler is version `latest` with the id `68601851e70ff03056f4558d875f3b3ee44ef67a1f1891c2745ab7941d450142`.

**Comment by philwinder** [comment]
Hi Francis,
I suspect the issue is because we only sopport mesos 22.1 at the moment. We haven't tested with 23 yet. So my guess is that we are expecting files that are no longer there in 23.

Can you retry with 22.1?

Thanks, Phil

**Comment by F21** [comment]
Hey Phil,

I just set up mesos 0.22.1 with Marathon 0.10.1 and am still seeing the same problem.

This time, I didn't get any output in `stdout` or `stderr` of the sandbox, but if I inspect the docker daemon on the node it was launching on, I see:

```
core@core-01 ~ $ sudo docker ps -a
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS                     PORTS               NAMES
5d82fa6cad6c        mesos/elasticsearch-scheduler   "/bin/sh -c 'echo 'N   4 minutes ago       Exited (1) 4 minutes ago                       mesos-22466992-d6d6-4a8d-9f83-79ac65200ca4
446a28ba9c2f        mesos/elasticsearch-scheduler   "/bin/sh -c 'echo 'N   5 minutes ago       Exited (1) 5 minutes ago                       mesos-4a659be5-33a4-48a9-a1e9-09142a0d0d40
core@core-01 ~ $ docker inspect  -f "{{.Name}} {{.Config.Cmd}}" $(docker ps -a -q)
/mesos-22466992-d6d6-4a8d-9f83-79ac65200ca4 {[-c echo 'No such file or directory'; exit 1]}
/mesos-4a659be5-33a4-48a9-a1e9-09142a0d0d40 {[-c echo 'No such file or directory'; exit 1]}
```

**Comment by philwinder** [comment]
Because you're getting that error message so early, and no other error messages, I has to be an issue with your environment. E.g. old docker version or something.

Can you describe your environment (e.g. hardware, os, etc.), provide version numbers, and we will try and recreate your problem. How have you installed mesos? Have you installed zookeeper?

**Comment by philwinder** [comment]
Oh and I see you used mesos.master for the IP address. I presume you have mesos DNS set up and working? Can you ping that hostname? If not, try using an IP address.

**Comment by F21** [comment]
Hey Phil,

The OS is CoreOS 794.0.0. Marathon is 0.10.0, Java is 8 and mesos is 0.22.1. Docker is 1.7.1 (comes with CoreOS). Zookeeper is 3.4.6 and mesos-dns is the latest HEAD.

Marathon, mesos, zookeeper and mesos-dns are compiled binaries that runs natively on CoreOS (not inside containers).

Pinging `master.mesos` and `leader.mesos` works from any node.

I will try using an IP and report back.

**Comment by F21** [comment]
Just tried using an ip address, but still the same problem.

**Comment by philwinder** [comment]
And how did you install marathon/mesos/etc on core os. Through the package manger, or via a third party? Did you use any install scripts? If so, can you provide them?

(Just so we can recreate your environment quickly)

On 6 Sep 2015 7:45 am, Francis Chuang <notifications@github.com> wrote:

Just tried using an ip address, but still the same problem.

**Comment by F21** [comment]
I have a bunch of scripts that builds the binaries and places them in a zip. Would it work if I uploaded a tar.xz of the compiled binaries onto bintray and then you can pull it down and throw them onto a coreos cluster to set up?

**Comment by philwinder** [comment]
Yes please. The easier you can make it for us to recreate your environment, the sooner we will be able to find an answer for you.

Thanks, Phil

On 6 Sep 2015 7:56 am, Francis Chuang <notifications@github.com> wrote:

I have a bunch of scripts that builds the binaries and places them in a zip. Would it work if I uploaded a tar.xz of the compiled binaries onto bintray and then you can pull it down and throw them onto a coreos cluster to set up?

**Comment by F21** [comment]
Hey Phil,

The packages are now on bintray. Each archive includes mesos, zookeeper, exhibitor (if you want to use it to manage zookeeper), marathon, mesos-dns and java 8.

Unfortunately, bintray had some file size limits. They are uploaded on to a different host instead:

Mesos-0.22.1: http://www.filedropper.com/mesos-0221tar

Mesos-0.23.0: Soon

The best way to launch CoreOS is using vagrant: https://github.com/coreos/coreos-vagrant

This should get you a quick CoreOS cluster up and running. Simply SCP the archive onto the CoreOS nodes, extract them and you should have the binaries.

**Comment by F21** [comment]
Sorry for the delay! Had issues finding a decent file host.

Mesos 0.22.1 http://www.mediafire.com/download/bgt5wz5y2tury5j/mesos-0.22.1.tar.xz
Mesos 0.23.0 http://www.mediafire.com/download/9yy791vbg4eaa88/mesos-0.23.0.tar.xz

**Comment by F21** [comment]
I have discovered the problem. The following options must be set when launching the mesos-slave binary.

First, `--launcher_dir` must be set to `/path/to/mesos/libexec/mesos/` so that it can find the required sub-binaries.

Second, the `--executor_environment_variables` flag must be used to set the `LD_LIBRARY_PATH` environment variable to the mesos `lib` directory: `--executor_environment_variables='{"LD_LIBRARY_PATH": "/path/to/mesos/lib/"}'

**Comment by a-nldisr** [comment]
FYI this framework launches on Mesos 0.23.0 with Marathon 0.10.0 without a problem. :+1:

**Comment by sergeygalkin** [comment]
Hi, the same issue.
mesos - 0.27.0
marathon - 0.15.2
I am trying to launch 1 simple docker application with nginx with 500 instances on cluster with 189 HW nodes
ID /1f532267a08494e3081c1acb42d273b7
Command Unspecified
Constraints Unspecified
Dependencies Unspecified
Labels Unspecified
Resource Roles Unspecified
Container
{
  "type": "DOCKER",
  "volumes": [],
  "docker": {
    "image": "nginx",
    "network": "BRIDGE",
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 0,
        "servicePort": 10000,
        "protocol": "tcp"
      }
    ],
    "privileged": false,
    "parameters": [],
    "forcePullImage": false
  }
}
CPUs 1
Environment Unspecified
Executor Unspecified
Health Checks 
[
  {
    "path": "/",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 300,
    "intervalSeconds": 60,
    "timeoutSeconds": 20,
    "maxConsecutiveFailures": 3,
    "ignoreHttp1xx": false
  }
]
Instances 500
IP Address Unspecified
Memory 256 MiB
Disk Space 50 MiB
Ports 10000
Backoff Factor 1.15
Backoff 1 seconds
Max Launch Delay 3600 seconds
URIs Unspecified
User Unspecified

Deployment stopped on Delayed, only about 360-370 of 500 instances are successful. In the stdout in the failed mesos tasks I see "No such file or directory"
As I see in /var/log/upstarе/docker.log with enabled debug mesos sometimes try to start containers with strange Cmd ("Cmd":["-c","echo 'No such file or directory'; exit 1"]) and this task failed. Sometime everything is ok   "Cmd":null and task in RUNNING state
Part of the log  available in http://paste.openstack.org/show/491122/

**Comment by philwinder** [comment]
@sergeygalkin: This is a mesos issue I'm afraid. Not a framework one. 

But on another note, can we use your cluster? :-) That's the largest I've heard of.

**Comment by sergeygalkin** [comment]
@philwinder I found this issue and post comment JFYI. I also opened https://issues.apache.org/jira/browse/MESOS-4977  
Sorry but cluster is very busy in our R&D :)
