### ISSUE TITLE
Refactor offers method

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#292]
The long offers method is horrible.
Refactor into a state machine to handle scaling logic. Refactor with testing in mind.

**Comment by jhftrifork** [comment]
This is presumably talking about [our `resourceOffers` implementation](https://github.com/mesos/elasticsearch/blob/659d85c247ba1eaf92d875ec6017a61789888586/scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchScheduler.java#L91-L127)

**Comment by jhftrifork** [comment]
One improvement I would like to see is that *all* the reasons for an offer being declined are logged, rather than just the first thing that failed.

**Comment by jhftrifork** [comment]
We should also refactor or remove [this `ResourceCheck` class](https://github.com/mesos/elasticsearch/blob/659d85c247ba1eaf92d875ec6017a61789888586/scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ResourceCheck.java). It makes no sense to my mind.

What I would like to see is a `ResourceCheck` which is a predicate over `Protos.Offer` objects. Something like

```
@FunctionalInterface
interface OfferCheck {
  // returns a list of reasons for failure; success is signaled by the empty list
  List<String> problemsWithOffer(Protos.Offer offer);
}
```

**Comment by jhftrifork** [comment]
We can then easily wrap up the logic of logging *all* errors with something like

```
class SatisfyAll implements OfferCheck {
  List<OfferCheck> checks;
  List<String> problemsWithOffer(Protos.Offer offer) {
    return checks.stream().flatMap(OfferCheck check -> check(offer)).collect(Collectors.toList());
  }
}
```

**Comment by frankscholten** [comment]
Good idea. This method should return as soon as possible so it's good to first check for problems.
