### ISSUE TITLE
Test auth in system tests

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#304]
Might require modification of mini-mesos.

**Comment by jhftrifork** [comment]
Created issue on mini-mesos https://github.com/ContainerSolutions/mini-mesos/issues/71

**Comment by jhftrifork** [comment]
Will create test first using the simple `MESOS_ACLS` environment variable.

**Comment by jhftrifork** [comment]
Working on this on https://github.com/mesos/elasticsearch/tree/304-test-auth-in-system-tests

**Comment by philwinder** [comment]
Fixed in #405
