### ISSUE TITLE
Propagate SIGNAL through to jvm

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#314]
When killing or stopping a container, it passes the appropriate signal ENTRYPOINT or CMD of the docker file. Because we don't propagate through to the JVM, the JVM won't stop and docker will just issue a SIGKILL command. This means that any shutdown hooks will not fire.

For us, that is a bash shell script. So the shell script should propagate the signal through to the jvm. See this for an example:
http://veithen.github.io/2014/11/16/sigterm-propagation.html

**Comment by frankscholten** [comment]
Docker 1.9 supports STOPSIGNAL which might be useful here.

https://blog.docker.com/2015/11/docker-1-9-production-ready-swarm-multi-host-networking/

**Comment by frankscholten** [comment]
Closing as we will be using the official Docker image in 0.8.0
