### ISSUE TITLE
Add GUI support for multiple ES clusters managed by a single framework instance

### ISSUE THREAD

**Issue by jrslv** [mesos/elasticsearch#317]

**Comment by mwl** [comment]
I don't see why this would ever happen. If you want multiple ES clusters you should just start multiple schedulers

**Comment by jrslv** [comment]
@frankscholten what do you think?

**Comment by frankscholten** [comment]
@mwl Good point. It won't really happen. It might be useful for snapshot restore but let's look at it then.
