### ISSUE TITLE
Reimplement scheduler unit tests

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#321]
For a previous version the scheduler unit tests were commented out due to refactoring. Reimplement these tests.

See: https://github.com/mesos/elasticsearch/blob/master/scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchSchedulerTest.java

**Comment by mwl** [comment]
Will be solved by #325

**Comment by mwl** [comment]
Fixed by #325.
