### ISSUE TITLE
Elasticsearch Data Directory Option for Variables

### ISSUE THREAD

**Issue by WalterDalton** [mesos/elasticsearch#372]
Can we have an option to use a node specific name in the --dataDir?  This would allow us to use a networked storage with mesos cluster so that if a node does die, we can spin it back up and it can access it's own data.   I suppose,  the --dataDir is in the container now, could we have the scheduler have an option to mount a volume to the executor container that has the ability to to have variables based on node name?

**Comment by philwinder** [comment]
`--dataDir` Mounts a docker volume onto the host. The path can be whatever you like, but is fixed.

As for "node specific", do you mean something like a `--dataDir`, then a flag saying `--nodeSpecificDataDir` where files would be written to `$(dataDir)/slaveID`?

I like that idea, does that suit you?

**Comment by WalterDalton** [comment]
So is the --dataDir the location in the container, or that the location that is mounted on the host. (I see what you wrote, but I am unclear on which the dataDir value is).   I am going assume this is the host specific volume rather than the location in the container as I would imagine that is (or should be hard coded (what reason would one ever have to change that if it's in a container?)

So let me retype what I think your saying to make sure we are on same page on the nodeSpecificDataDir flag you proposed.  

I could specify --dataDir and this would be the base of where my data was located. 
--dataDir /mnt/sharedstorage/elasticsearch

then if I also specified --nodeSpecificDataDir 

--nodeSpecificDataDir

It would take the dataDir and for each node in my cluster, automatically create a folder (if it doesn't exist) given a nodeID. 

You use "slave ID", should we make it node specific rather than slave? The idea here is that if there is a crash of the es node, and mesos spun up that es node somewhere else, the node id would be the same, even if the slave id is different. It would first check to see if the directory exists, if it does, it would use the data that is there. Thus "persisting" to the shared storage.  

Example: A three node cluster prior to spin up, the only directory that exists is
/mnt/sharedstorage/elasticsearch

When we spin up a three node cluster, the following dirs are created and the three nodes use them for storage:

/mnt/sharedstorage/elasticsearch/node1
/mnt/sharedstorage/elasticsearch/node2
/mnt/sharedstorage/elasticsearch/node3


If that is what you are thinking, then we are in agreement: it would work perfectly like that.  The only addition I would make is to add an option to add a directory level for cluster name. 

--dataDir /mnt/sharedstorage/elasticsearch
--clusterSpecificDataDir
--nodeSpecifcDataDir

That way, we could have multi-tenancy very easily. 
Cluster Name: mesos-es-prod
/mnt/sharedstorage/elasticsearch/mesos-es-prod/node1
/mnt/sharedstorage/elasticsearch/mesos-es-prod/node2
/mnt/sharedstorage/elasticsearch/mesos-es-prod/node3

Cluster Name: mesos-es-dev
/mnt/sharedstorage/elasticsearch/mesos-es-dev/node1
/mnt/sharedstorage/elasticsearch/mesos-es-dev/node2
/mnt/sharedstorage/elasticsearch/mesos-es-dev/node3

I am interested in your thoughts.
