### ISSUE TITLE
Upgrade executor IP Address reporting to use mesos proto's in 0.25

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#373]
After upgrading to 0.25, alter the IP Address reporting to use proper mesos protocol buffer messages in the FrameworkMessage.

Waiting for 0.25 upgrade.

**Comment by mwl** [comment]
Framework has been upgraded to use Mesos 0.2.5

**Comment by frankscholten** [comment]
Closing is the executor will be removed in 0.8.0
