### ISSUE TITLE
Executor running on centos7 don't get eth0 ip

### ISSUE THREAD

**Issue by commarmi76** [mesos/elasticsearch#387]
Centos 7 change the names of the interfaces and not use eth0. For example my first network card is enp2s0f0.

I'm testing master  (0.5.1.)

executor log:
[WARN] 2015-10-27 12:31:08,091 org.apache.mesos.elasticsearch.executor.mesos.ElasticsearchExecutor launchTask - Unable to obtain eth0 ip address
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.apache.mesos.elasticsearch.common.AdaptorIPAddress.eth0(AdaptorIPAddress.java:25)
	at org.apache.mesos.elasticsearch.executor.mesos.ElasticsearchExecutor.launchTask(ElasticsearchExecutor.java:110)

scheduler log:
[ERROR] 2015-10-27 12:34:35,799 org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] log - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Inet address may not be null] with root cause
java.lang.IllegalArgumentException: Inet address may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.HttpHost.<init>(HttpHost.java:151)
	at org.apache.http.HttpHost.<init>(HttpHost.java:191)
	at org.apache.mesos.elasticsearch.scheduler.controllers.SearchProxyController.toHttpHost(SearchProxyController.java:76)

**Comment by philwinder** [comment]
Hi commarmi76.
That is very annoying! How would you suggest that the IP address is obtained for Centos 7? I could fall back to simply selecting the first adaptor with an IP address?

**Comment by commarmi76** [comment]
I guess you are launching the executors from the scheduler, right ?
Why don't get the hostnames of the slaves from mesos, and resolve the ip ?

**Comment by philwinder** [comment]
We can't do that, because we're not guaranteed to have a DNS server. Yes mesos provides the hostnames, but that's it. So if there is no DNS server, you can't resolve the IP address.

Can you provide a dump of your ifconfig on one of your centos boxes. I just spun up a centos 7 box and it did use eth0.

**Comment by commarmi76** [comment]
Ok, maybe you can send the hostname to the executors, that can resolve its own hostname.


enp2s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.y.z  netmask 255.255.255.0  broadcast x.y.z.255
        ether xx:xx:xx:yy:yy:yy  txqueuelen 1000  (Ethernet)
        RX packets 115870242  bytes 44677126917 (41.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 127272714  bytes 87353840797 (81.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 28  memory 0xfb000000-fb7fffff  

enp2s0f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.y.z  netmask 255.255.255.0  broadcast x.y.z.255
        ether xx:xx:xx:yy:yy:yy  txqueuelen 1000  (Ethernet)
        RX packets 133568977  bytes 24503389439 (22.8 GiB)
        RX errors 0  dropped 7906  overruns 0  frame 0
        TX packets 111920719  bytes 39033842695 (36.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 40  memory 0xfa000000-fa7fffff  

enp2s0f1.102: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether xx:xx:xx:yy:yy:yy  txqueuelen 0  (Ethernet)
        RX packets 4189006  bytes 194627670 (185.6 MiB)
        RX errors 0  dropped 45  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 8456934  bytes 624069449 (595.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8456934  bytes 624069449 (595.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet x.y.z  netmask 255.255.255.0  broadcast x.y.z.255
        ether xx:xx:xx:yy:yy:yy  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by philwinder** [comment]
I'm a bit confused here, as I though docker would always create a virtual eth0 inside the container. Let me re-read the documentation.

**Comment by philwinder** [comment]
Yes, see this documentation. There should always be an eth0:
https://docs.docker.com/articles/networking/#how-docker-networks-a-container

**Comment by commarmi76** [comment]
so sorry, I forgot to mention I'm not using docker.

**Comment by philwinder** [comment]
Ah, there we go. That makes perfect sense. Because you're using jars, it's using the native adaptors, which can be called whatever they like. I'm afraid that might take some more time to think about the best way to do it, and to do some testing. So I won't push it into this release; I will wait until 0.5.2. I'll create a new bug that describes the problem. Thanks.
