### ISSUE TITLE
Revert networking changes to use hostname

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#392]
Use hostname for obtaining the ip address. This is required for Mesos cluster use, so should be properly setup by the user. If it is not, then the cluster will not work properly and the addresses won't be correct. This places the emphasis on the user to use a correct hostname rather than trying to work around it in the code.

Should also fix #388 

[ ] - Remove old networking code
[ ] - Re-add hostname resolution
[ ] - Fix minimesos system tests.

**Comment by mwl** [comment]
Thanks!
