### ISSUE TITLE
Use Mesos DNS for node discovery in Elasticsearch Mesos Cloud Plugin

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#4]
Currently we use the Master's state file to discover nodes in the cluster. Replace this with Mesos DNS node discovery mechanism.

- [x] Expose services in mesos-dns
- [x] Deploy mesosphere/mesos-dns
- [ ] Configure DNS on all nodes
- [x] Look up ES instances through DNS in Mesos-cloud plugin
- [ ] Automate adding `prepend domain-name-servers 10.11.142.163;` to `/etc/dhcp/dhclient.conf` on all nodes

**Comment by mwl** [comment]
Used config

```json
{
  "masters": ["10.11.142.163:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["8.8.8.8"],
  "timeout": 5,
  "listener": "0.0.0.0",
  "email": "root.mesos-dns.mesos"
}
```

**Comment by mwl** [comment]
mesos-dns has been started on the master node with

```
$ sudo docker run --restart=always -d --name mesosdns -p 53:53 -p 53:53/udp -v /etc/mesos-dns.conf:/config.json mwldk/mesos-dns:0.1.1-srvfix mesos-dns -config=/config.json -v=2
```

Content of `/etc/mesos-dns.conf`:

```JSON
{
  "masters": ["10.11.142.163:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["8.8.8.8"],
  "timeout": 5,
  "listener": "0.0.0.0",
  "email": "root.mesos-dns.mesos"
}
```

**Comment by mwl** [comment]
Temporary fix. Deployed mesos-dns in docker on all hosts and added `prepend domain-name-servers 127.0.0.1;` to `/etc/dhcp/dhclient.conf`

**Comment by mwl** [comment]
So, turns out there's a firewall in GCE which blocks all privileged ports. Add 53/udp and 53/tcp as an exception to that.
