### ISSUE TITLE
option to use IP addresses instead of hostname

### ISSUE THREAD

**Issue by sadovnikov** [mesos/elasticsearch#418]
when deploying jar version of the framework on ```minimesos``` cluster, hostnames do not get resolved on mesos agents and on the host system. Extending the framework with ```--no-hostname_lookup``` configuration option (like on http://mesos.apache.org/documentation/latest/configuration/) would help. 

The implementation will involve changing:
* ```Configuration#getFrameworkFileServerAddress()``` to make executor code downloadable by fetchers on mesos agents;
* ```FrameworkInfoFactory#setWebuiUrl()``` to make link on Mesos UI resolvable

**Comment by philwinder** [comment]
1. Don't use the jar version. 99% of people should use the docker version. Only people that really don't want to use docker should use the jar version.
2. The fact that your hostnames are not resolvable is not a responsibility of the framework. It is the responsibility of your network infrastructure.
3. Where would the ip address be parsed from? In bridge mode, the container might not even get an IP address. In host mode, the ip address might be adapter1, adaptor2, eth0, wan0.... which one should it choose? 

So I'm going to close this as wontfix. If you want the ability to force it to report a specific IP address, then thats a different and reasonable request. But we can't automate this in a reliable fashion, so it is up to the user to ensure that the hostnames are resolvable.

**Comment by philwinder** [comment]
Implementing to ensure it works with minimesos out of the box.

**Comment by philwinder** [comment]
Fixed in #430.
