### ISSUE TITLE
Docker Requirement

### ISSUE THREAD

**Issue by WalterDalton** [mesos/elasticsearch#42]
Does this framework require the docker containers to run? If so will there be options to use and set local docker registries so we don't have to pre distribute the containers? If not will there be directions on how to get this setup as a native framework with no Docker containers? And also, if that's the case, will there be options to build without building the docker containers. 

Thanks!

**Comment by prasincs** [comment]
It doesn't need docker containers to run, but the build step requires docker. I have successfully run it on clusters without docker but had to use a build server with docker to get the assets.

**Comment by frankscholten** [comment]
You can skip the docker build of the scheduler module with

```
gw clean build -x buildDockerImage
```

**Comment by WalterDalton** [comment]
Sorry for my delay in responding to this, but I am confused on how to get things up and running without Docker. I'd like to just it running, it built succesfully (thanks Frank) but now I can't find the elasticserach-cloud-mesos referenced in the deploy. I woud imagine I need to run the scheduler and executor? or does one call the other? Without this Zip I Don't see how it works? 

 scp elasticsearch-cloud-mesos/build/docker/elasticsearch-cloud-mesos.zip

**Comment by frankscholten** [comment]
We recently removed elasticsearch-cloud-mesos because we now use the Elasticsearch Zookeeper plugin https://github.com/trifork-leeds/elasticsearch-zookeeper.

To quickly get up and running try the docker-compose file in systemTest/src/test/resources/mesos-es. It starts a containerized Mesos cluster with a single master and three slaves as well as the scheduler. For more information check the README.

**Comment by WalterDalton** [comment]
So then in this case docker would be a requirement? This is going to
require a lot of down loading depending on which nodes get what services.
Will elastic search on mesos run as a native framework or will docker
always be a component?

**Comment by WalterDalton** [comment]
I guess what are the goals of the project here, to be able to run natively on Mesos, or to have to run through Docker?  I am getting mixed messages on the requirement of Docker based on these responses and my initial question. 

Thanks!

**Comment by frankscholten** [comment]
For now the scheduler and executor run in Docker so Docker is a requirement.

**Comment by WalterDalton** [comment]
Is it possible to build the Docker containers and push them to a local registry? (Obviously that's possible) I guess the question would be can we then set the use of a local docker registry?  I am trying to avoid having all my nodes when they get the command to do something to have to go to the internet to download images that can be rather large. (Especially when they can be prebuilt and stored on a registry) (Not much bandwidth here).  

Is this the strategy long term for this project?  Are there plans to run this natively as well? If Docker will be a requirement, I'd recommend putting that on the readme so people understand. For those working in the project, it may seem trivial, but for those coming into this, and seeing other projects and how they work, a docker requirement isn't a given.

**Comment by frankscholten** [comment]
We are planning on making images configurable https://github.com/mesos/elasticsearch/issues/71
