### ISSUE TITLE
API endpoint with overall cluster health

### ISSUE THREAD

**Issue by remmelt** [mesos/elasticsearch#427]
In order to integrate with the Mantl UI, we need an endpoint that the UI process can call that will report the overall health of the ES cluster. It's enough to pass through ElasticSearch's green/yellow/red cluster status. The endpoint does not currently need to conform to any generic standard (there isn't one) so implement however you like.

https://github.com/ciscocloud/mantl-ui-frontend

**Comment by tymofii-polekhin** [comment]
@remmelt you can get cluster health like that `http://<es-executor>:<http-port>/_cluster/health`
you will get something like this
```
{
  "cluster_name" : "mesos-elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 7,
  "number_of_data_nodes" : 7,
  "active_primary_shards" : 111,
  "active_shards" : 222,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}
```
