### ISSUE TITLE
Can we pass docker run parameters to executor.

### ISSUE THREAD

**Issue by pradeepchhetri** [mesos/elasticsearch#453]
Hello,

I am trying to use mesos-dvdi module for persistence of elasticsearch data. For attaching EBS disk to mesos-slaves on which es-executors are running, I need to pass some docker parameters like "--volume-drive=rexray". Is there any way i can pass define it in marathon configuration of scheduler which will automatically pass them as docker parameters to executor.

Thanks.

**Comment by philwinder** [comment]
No you can't at the moment. Could you define this statically on each host somehow? Is this a feature you would be interested in?

**Comment by philwinder** [comment]
This is how our tests do it:
```
        HttpResponse<JsonNode> response = Unirest.put("http://" + ipAddress + ":" + WEBUI_PORT + "/v1/cluster/elasticsearchNodes").header("Content-Type", "application/json").body(newNumNodes.toString()).asJson();
```
So yes, you need to send the number of nodes as the body data.

**Comment by paperage** [comment]
Is there a way to pass parameters to executor like " --ulimit memlock" or "--ulimit nofile"  to make an optimization ?
