### ISSUE TITLE
Running Mesos Elasticsearch on DCOS 1.4 via Amazon fails to initialize

### ISSUE THREAD

**Issue by rtrujill007** [mesos/elasticsearch#454]
###### Description:
Running Mesos Elasticsearch on DCOS 1.4 using [Amazon](https://mesosphere.com/amazon/) fails to initialize. I followed the steps to enable Mesos Elasticsearch on DCOS (see below), however i never see the Elasticsearch service get intialized properly. When i look at the logs i can see the errors from the Mesos UI and the this error in the stderr (see below for more info).

```
Failed to detect a master: Failed to parse data of unknown label 'json.info'
```

###### Steps To Reproduce:
1. Setup a DCOS cluster on Amazon
2. Run the following commands:
  
  ```
  dcos config prepend package.sources https://github.com/mesosphere/multiverse/archive/version-1.x.zip
  dcos package update
  dcos package install elasticsearch
  ```
3. Open the Mesos UI, notice the the **Failures** under the completed tasks.
![mesos-ui](https://cloud.githubusercontent.com/assets/6181677/12270778/9c95db2c-b90c-11e5-849b-aa0eb8144300.png)
4. Click on on of the Failed taks and open the **Sandbox**, then click on the **stderr** ui, notice the error:
![stderr](https://cloud.githubusercontent.com/assets/6181677/12270736/64f603fe-b90c-11e5-8c29-116ed89f0c05.png)

**Comment by philwinder** [comment]
@rtrujill007 
The version on the universe is so out of date, I would be surprised if it works. Our PRs to update their repos are often ignored so we stopped updating them.
I would recommend installing using the instructions in the documentation, via marathon. Not using DCOS's tools.
