### ISSUE TITLE
mesos 0.26 support

### ISSUE THREAD

**Issue by ryane** [mesos/elasticsearch#457]
While the scheduler appears to run ok, executors fail to launch on mesos 0.26 with the following error:

```
Failed to load native Mesos library from /usr/lib/libmesos-0.26.0.so
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/libmesos-0.26.0.so
```

According to #422, I assume mesos/elasticsearch-base would have to be rebuilt against mesos 0.26 (amongst other things, perhaps). I understand there are compatibility challenges but it would be nice if the framework wasn't so tightly bound to a specific version.

**Comment by frankscholten** [comment]
We are focusing on creating a stable ELK setup so we won't be upgrading to 0.26.0 soon.

**Comment by h0tbird** [comment]
+1

**Comment by blue666man** [comment]
+1

**Comment by XumetBDN** [comment]
+1

**Comment by philwinder** [comment]
@ryane I would love this too. But nearly every time there has been a Mesos upgrade, the code won't compile, let alone run. But yes, this is the future. Hopefully the changes will become less breaking over time and we can mount the host's mesos libraries.

**Comment by frankscholten** [comment]
We can also look at moving to the scheduler HTTP API. 0.27 supports executor HTTP API

**Comment by philwinder** [comment]
Blocked by: https://issues.apache.org/jira/browse/MESOS-4449
Agents keep failing about 1 time in 10 on the system tests.

**Comment by philwinder** [comment]
All,
We won't be upgrading to 0.26 because of the bug above. The fix is destined for 0.27.

**Comment by siddharthist** [comment]
Is Mesos 0.27 supported yet?

**Comment by philwinder** [comment]
Yes and yes. It works without changes.
