### ISSUE TITLE
Investigate removal of executor, to allow use of official images/binaries

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#475]
The may not be a need for the executor. All of the health and scaling logic is contained within the scheduler. In order to simplify the use of official images/binaries and in the installation of plugins, investigate whether we can remove the executors.

**Comment by philwinder** [comment]
Proposal:
- [ ] Remove executor
- [ ] Reinstate docker mode elasticsearch using official docker image
- - [ ] Alter TaskInfo code to start docker image
- - [ ] Alter healthcheck code to ping elasticsearch
- [ ] Reinstate jar mode elasticsearch using official ES binaries
- - [ ] Use Mesos URIs to download and extract ES binaries
- [ ] Think about
- - [ ] Discovery and IP addresses
- - [ ] Overriding ES settings (Parameters can be passed to the cmd, or config dir mounted: https://hub.docker.com/_/elasticsearch/)
- - [ ] Data persistance directory (https://hub.docker.com/_/elasticsearch/)

**Comment by frankscholten** [comment]
Also  add code to handle task status

**Comment by philwinder** [comment]
Fixed in #488
