### ISSUE TITLE
With large amounts of data, when scaling, start up times out

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#481]
If there are large amounts of data in a database, it takes some time for the data to be synchronized across the network. Currently there is a 60 second timeout that kills the ES node if it hasn't started. However, if there is enough data, the initial synchronisation can take more than 60 seconds. Hence no nodes get started.

**Comment by frankscholten** [comment]
Should we increase the timeout?

**Comment by philwinder** [comment]
Maybe we should remove the timeout. Increasing the timeout just sets the amount of data threshold higher. It doesn't solve the problem.

Ideally, we would remove the timeout and interrogate ES to find out what is going on. If just synchronising, then leave it alone. If failure, kill it.
