### ISSUE TITLE
Framework hard codes the ZK endpoint /mesos

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#483]
https://github.com/mesos/elasticsearch/blob/master/commons/src/main/java/org/apache/mesos/elasticsearch/common/zookeeper/formatter/MesosZKFormatter.java#L18

Some people don't have the mesos endpoint at /mesos. Parse this from the passed in zk address.

**Comment by frankscholten** [comment]
Merged in https://github.com/mesos/elasticsearch/pull/492
