### ISSUE TITLE
Health check issue

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#486]
User on 0.23, running 0.25 framework.
When started, the scheduler said that it found three tasks in TASK_RUNNING state. And then proceeded to blurt out ```[DEBUG] 2016-02-04 15:17:07,556 org.apache.mesos.elasticsearch.scheduler.healthcheck.ExecutorHealth run - Task is alive. It has been 0 ms since the last update.
``` 
For the rest of eternity. Even though there were no tasks running. 
```
No idea what the cause is.

**Comment by frankscholten** [comment]
Closing this one as executors as well as health checks will be removed in 0.8.0. See https://github.com/mesos/elasticsearch/issues/475
