### ISSUE TITLE
Stale data when scaling nodes

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#487]
Start with 8 nodes. Insert data. Scale down to < 8 nodes. Delete all data. Scale back up to 8 nodes. The stale data left on the eighth node will be reinserted into the DB.

**Comment by frankscholten** [comment]
So it seems the root cause is that data is not properly deleted? Could this be reproduced with a single node?

**Comment by philwinder** [comment]
Correct. The data is not deleted when scaling down. No, not with a single node, because the code will prevent you from scaling to less than 1. But you could replicate it with 2 or more nodes.

**Comment by frankscholten** [comment]
I could not reproduce this issue but I added a system test for it. See https://github.com/mesos/elasticsearch/pull/498

**Comment by philwinder** [comment]
Fixed in #502
