### ISSUE TITLE
Allocation doesn't start automatically

### ISSUE THREAD

**Issue by TheStigger** [mesos/elasticsearch#500]
I have elasticsearch cluster with 3 nodes. Also, I have an index with 1 replica and 3 shardings. When I kill executor on one node, framework successfully starts new executor. But shards don't automatically allocate to the new executor.
`_cluster/health` looks the same, as before killing executor (green status). But I have `{"error":"NullPointerException[null]","status":500}` when try to get `_cat/shards`.
My cluster doesn't see any changes and doesn't try to allocate missing shards though `cluster/state/nodes` looks right.
After updating any settings, like `number_of_replicas` or `cluster.routing.allocation.enable`, `_cluster/health` looks right (yellow status for a while) and elasticsearch starts allocations.

**Comment by philwinder** [comment]
Interesting. Thanks for the report. AFAIK, you should never get unallocated shards with the ES settings, because of the auto-replicas. Which suggests to me that it is something to do with your configuration.

Could you please post (if applicable):
- Marathon JSON / Command used to start the framework
- Custom ES configuration file
- Any settings you have applied to the ES nodes through the HTTP interface.
- Anything else you have done that is non-standard.

I say this, because we have system tests that test this and they have never produced the results you describe.

Thanks, Phil

**Comment by TheStigger** [comment]
I'm sorry. I've forgotten to say, that I use 0.6 version. Maybe that's the problem.

Marathon JSON:
```
{
  "id": "elasticsearch",
  "cpus": 0.2,
  "mem": 512,
  "instances": 1,
  "cmd": "wget -q https://jitpack.io/com/github/mesos/elasticsearch/scheduler/f415b3c8ea/scheduler-f415b3c8ea.jar -O es-scheduler.jar && java -jar es-scheduler.jar --frameworkName elastic-search --frameworkUseDocker false --zookeeperMesosUrl zk://zookeeper.service.consul:2181 --elasticsearchCpu 2 --elasticsearchRam 8192 --elasticsearchDisk 30720 --elasticsearchSettingsLocation https://gist.githubusercontent.com/TheStigger/c769b1857c9f0fa7b0af/raw/bcca7c69856cb1062da50bc54e47004abe4a290f/elasticsearch_settings.yaml",
  "env": {
    "JAVA_OPTS": "-Xms256m -Xmx512m"
  },
  "ports": [31100],
  "requirePorts": true,
  "healthChecks": [
    {
      "gracePeriodSeconds": 120,
      "intervalSeconds": 10,
      "maxConsecutiveFailures": 6,
      "path": "/",
      "portIndex": 0,
      "protocol": "HTTP",
      "timeoutSeconds": 5
    }
  ]
}
```

Custom ES configuration: [link](https://gist.githubusercontent.com/TheStigger/c769b1857c9f0fa7b0af/raw/bcca7c69856cb1062da50bc54e47004abe4a290f/elasticsearch_settings.yaml).

Also, I've overridden default cluster settings though defaults are the same (just in case).
```
{
  "persistent" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : "all"
        }
      }
    }
  }
}
```

**Comment by philwinder** [comment]
Those settings look fine. And the bottom change shouldn't make much difference. So the only think I can suggest is to try the most recent version. This introduces manual scaling, so maybe you can do some tests with manual scaling too. This is the link to the most recent jar (we've started releasing them on GH, not jitpack. That was a bit unstable):
https://github.com/mesos/elasticsearch/releases/download/0.7.1/scheduler-0.7.1.jar

**Comment by TheStigger** [comment]
I have a slightly outdated mesos (0.23.0) version, so I can't update :(
I'll try to check allocation without the framework, maybe it is es problem, not yours.
