### ISSUE TITLE
JAR file for 1.0.0 release

### ISSUE THREAD

**Issue by siddharthist** [mesos/elasticsearch#521]
All other releases have had .zip, .tar.gz, and .jar files, but the 1.0.0 release doesn't have a .jar yet. Can one be posted? 

This is blocking easy integration with [mantl.io](http://mantl.io), because we fetch the JAR file using [a URL templated with the version](https://github.com/CiscoCloud/mantl/blob/a1d5bcb5432f887fbf7a8b4bd312a74aaa31cb13/roles/elk/defaults/main.yml#L10-L14).

**Comment by philwinder** [comment]
Hi @siddharthist. I was half way through the release when I found a bug with the custom ES settings. I'm fixing right now and will upload shortly.

**Comment by philwinder** [comment]
Done!

**Comment by siddharthist** [comment]
Thanks @philwinder!
