### ISSUE TITLE
use consistent filenames for releases

### ISSUE THREAD

**Issue by ryane** [mesos/elasticsearch#523]
It would be nice if the file name format was consistent and predictable across releases:

0.7.1: scheduler-0.7.1.jar
0.7.2: elasticsearch-mesos-scheduler-0.7.2.jar
1.0.0: elasticsearch-mesos-scheduler-1.0.0-withDependencies.jar

The changing format complicates automation.

**Comment by philwinder** [comment]
Understood. This was due to changes in the build file.

Would you like to suggest a naming convention that works for you?

**Comment by ryane** [comment]
as long as the file name format includes the version number and is consistent across releases, we should be fine. The name used for 0.7.2 would be great (elasticsearch-mesos-scheduler-0.7.2.jar)
