### ISSUE TITLE
Could not find any executable java binary in 1.0.0 release

### ISSUE THREAD

**Issue by garyelephant** [mesos/elasticsearch#529]
When I run elasticsearch using `elasticsearch-mesos-scheduler-1.0.0-withDependencies.jar`, it keeps promote:

```
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME
```

But it never occurred in `scheduler-0.7.1.jar` on the same machine, Is something wrong ?

My Java environment is 

```
$ which java
/usr/bin/java

$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by philwinder** [comment]
I've no idea @garyelephant, sorry. This is a system related issue, not a framework one. Are you sure you're looking on the right machine? Could your JAVA_OPTS be malformed?

To fix this I think you're going to have to provide us with a setup that demonstrates this issue.

Closing, but feel free to update this issue if you figure out the problem. Thanks.
