### ISSUE TITLE
Installing ES plugins when running in Jar mode on mesos?

### ISSUE THREAD

**Issue by zoza1982** [mesos/elasticsearch#534]
I haven't figured way to install plugins in Jar mode nor found any docs on it, but I was wondering ..... if this is true and not possible ...it's huge disadvantage running any serious production cluster in jar mode on mesos without having ability to install plugins like shield, marvel , watcher, kopf, head...etc.

I heard argument as  its better to run in Jar mode due to some docker bug...

**Comment by philwinder** [comment]
Hi @zoza1982. There are a number of ways, but I think the easiest is to override the containers/binaries. 

So for example, if you were using docker mode, you would extend the `elasticsearch` container with `FROM elasticsearch` and add you plugin to the container's plugins folder. If you were in jar mode, download the elasticsearch tar.gz, untar it, add you plugin and then re-tar it and upload it to somewhere where the binary is accessible from all hosts.

Then you can edit the respective configuration options to specify your own docker image / binary.

Hope that helps!

**Comment by zoza1982** [comment]
Thank Phil, I was aware of how to do it in container mode.
Jar was the one I haven't tackled yet. Thanks for valuable info!
