### ISSUE TITLE
Is the mesos elasticsearch ready for production use?

### ISSUE THREAD

**Issue by sjkyspa** [mesos/elasticsearch#538]

**Comment by a-nldisr** [comment]
Depends on your requirements for production.

**Comment by sjkyspa** [comment]
@a-nldisr 
I need it to collect the topbeat and logstash data in a PaaS. So it should be available all the time.

**Comment by philwinder** [comment]
@sjkyspa Of course! Define "production ready"? If it contains all the features you require, and you can use it without any stability issues, then yes, it is production ready. Only you can answer that.

For example, you'd consider various Linux distro's production ready, right? But new bugs are found all the time. Instances fail in ways we didn't anticipate. People use them in ways we couldn't comprehend.

So all I can suggest is try it. Test it. Try and break it. Keep using it until you have the confidence to deploy.
