### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by lguminski** [mesos/elasticsearch#54]
Even if nothing has changed, it takes lots of time to determine that nothing has changed in :scheduler:jar and :executor:jar tasks
```
:elasticsearch-cloud-mesos:processResources UP-TO-DATE
:elasticsearch-cloud-mesos:classes UP-TO-DATE
:elasticsearch-cloud-mesos:jar UP-TO-DATE                   <--- several minutes
:elasticsearch-cloud-mesos:assemble UP-TO-DATE
```
it looks the problem is caused due to shadowing grade plugin

**Comment by frankscholten** [comment]
Can't reproduce
