### ISSUE TITLE
--elasticsearchDisk  setting not being in effect

### ISSUE THREAD

**Issue by zoza1982** [mesos/elasticsearch#542]
Framework version 1.0.1

Hi, I tested --elasticsearchDisk  setting in both jar mode alone and container mode, and as it seems to be reflecting my option on Frameworkweb ui, but on another side, elasticsearch itself in both jar or container mode ...reports seeing full VM disk size .

![screen shot 2016-03-29 at 2 21 28 pm](https://cloud.githubusercontent.com/assets/11164593/14126097/aa2290de-f5c3-11e5-98f4-ad44823e3318.png)

Where via api query ...elasticsearch executor sees things differently.

![screen shot 2016-03-29 at 2 20 36 pm](https://cloud.githubusercontent.com/assets/11164593/14126100/aecfe87a-f5c3-11e5-86ac-c35009062f65.png)

**Comment by zoza1982** [comment]
I am currently testing it too see if its going to actually exceed allowable disk size per node.

**Comment by zoza1982** [comment]
I set limit to this time to 1gb for disk and it seems to not exceeding size. Standing still at 1GB per node, regardless of how much total size it sees.

![screen shot 2016-03-29 at 5 27 23 pm](https://cloud.githubusercontent.com/assets/11164593/14128203/9d8f77e6-f5d3-11e5-806b-4b4973d46ceb.png)

I guess we can close this issue as I learned how application works and sees resources as a framework.

**Comment by philwinder** [comment]
Hi @zoza1982. The disk option doesn't enforce the disk size. All it does is accept Mesos resources of a given disk size. E.g. If mesos offers 10GB, and you set --disk to 5GB, it will accept 5GB of that offer. It does not mean that the disk size is 5GB, or that it will be enforced to be that size. That's Mesos's job.

If you want to enforce the disk size, then you have to turn on disk isolation in Mesos. If you want to use a specific volume, then you'll have to mount that volume and set the disk location in the settings, or use external volumes.

**Comment by zoza1982** [comment]
thanks @philwinder for clarification. That makes sense.
