### ISSUE TITLE
 executor.log not present, does it require to be configured

### ISSUE THREAD

**Issue by rsingh2411** [mesos/elasticsearch#549]
This is not an issue, I was able to see scheduler.log in scheduler container, but executor logs were not present, Is any configuration required to enable them.

**Comment by philwinder** [comment]
Hi @rsingh2411 
No, that is not possible. The executors are running in different containers on different hosts. There is no log forwarding mechanism.

The two simplest things you can try:
1) Navigate to the executor sandbox and view the executor logs through the Mesos gui.
2) Use a log forwarder like the http://logstash.mesosframeworks.com/ framework to push all logs to a central location (e.g. elasticsearch.

Thanks, Phil
