### ISSUE TITLE
Not able to build scheduler docker images, manually

### ISSUE THREAD

**Issue by rsingh2411** [mesos/elasticsearch#551]
I have added some changes in scheduler code, as using custom elastic search with plugins installed.
I am using shield plugin for basic authentication, hence I need to pass credentials, hence had  to add changes in SearchProxyController.

It seems that mesos/elasticsearch-base:latest is removed officially from public repository.
Is this intended or is there any another way around this.

Following is the error
Sending build context to Docker daemon 81.81 MB
Step 1 : FROM mesos/elasticsearch-base:latest
Pulling repository docker.io/mesos/elasticsearch-base
Error: image mesos/elasticsearch-base:latest not found

**Comment by philwinder** [comment]
The Base image is in the commons folder. You can follow the build instructions in the documentation here:https://github.com/mesos/elasticsearch/blob/master/docs/index.md#how-to-run-on-mac

Furthermore, you don't need to rebuild to provide your own docker image. Look at the elasticsearchDockerImage setting: https://github.com/mesos/elasticsearch/blob/master/docs/index.md#how-to-install-on-marathon

Thanks, Phil
