### ISSUE TITLE
Allow user request for port "0" (which will be turned into a random port)

### ISSUE THREAD

**Issue by ftrossbach** [mesos/elasticsearch#553]
I have an issue with the DCOS elasticsearch package from Mesosphere Universe (https://github.com/mesosphere/universe/tree/version-2.x/repo/packages/E/elasticsearch/0). It is not yet possible to specify a custom configuration for the `elasticsearchPorts` property in this repository. 

I created my own repository and successfully managed to add custom http and transport ports. However, when I wanted to create a pull request for the Mesosphere Universe, I realized that I could not find a solution to specifically tell the elasticsearch scheduler "use these two ports if they're specified, of some random ports otherwise. Passing the value "0,0" as in Marathon to specify that I don't require a specific port lead to no ES instances starting up. Analysis of the code in this repo suggested that this is not supported and no ES instances were starting because port 0 is not on offer.

I will submit a pull request shortly, any feedback is appreciated.

**Comment by philwinder** [comment]
@ftrossbach, we haven't updated that repository for a long time and have no plans to do so.

Please install via the marathon commands specified in the documentation and you will have no problems either specifying random ports (by not passing a port specification) or fixed ports.

Thanks.

**Comment by ftrossbach** [comment]
Ah, I did not realized this issue was closed. I provided a pull request (https://github.com/mesos/elasticsearch/pull/554) that contributes this feature.

I still think this is worth having. I know that plain Marathon already allows me to run on specified ports, but this makes using fixed ports with DCOS repo (public or private) much easier.
