### ISSUE TITLE
Constrain one Elasticsearch task per worker node (slave)

### ISSUE THREAD

**Issue by metalseargolid** [mesos/elasticsearch#556]
Is there a way to configure Elasticsearch as installed with the mesos/elasticsearch framework to enforce one ES instance per slave when scaling up? For example, when I scale the ES instances from 3 to 5, I want the ES instances to be spun up on slaves 4 and 5 rather than slaves 1, 2, or 3, which already have ES tasks running on them.

**Comment by philwinder** [comment]
This is the default behaviour. It will do this out of the box.
Thanks - Phil
