### ISSUE TITLE
Add Hostname override flag

### ISSUE THREAD

**Issue by LLParse** [mesos/elasticsearch#559]
I am unable to use this framework in my environment. I am running v1.0.1 scheduler from within a Docker container. The hostname that registers in Mesos is the Docker container hostname, which cannot be resolved. 

Other frameworks allow explicitly setting the hostname by command line flag. An example of this pattern may be seen in [Marathon framework](https://mesosphere.github.io/marathon/docs/command-line-flags.html).

**Comment by philwinder** [comment]
Hi @LLParse. Please see the following flag in the documentation:
```
--useIpAddress
       If true, the framework will resolve the local ip address. If false, it
       uses the hostname.
       Default: false
```
Thanks, Phil.
