### ISSUE TITLE
Running elastic Search executors in Bridge Mode

### ISSUE THREAD

**Issue by rsingh2411** [mesos/elasticsearch#560]
Is there a way to run elastic search  executors in Bridge mode? 
Presently they run in Host mode.

**Comment by philwinder** [comment]
No, the HOST mode is hardcoded here:
https://github.com/mesos/elasticsearch/blob/master/scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/TaskInfoFactory.java#L160

In real life, ports are allocated by Mesos and ES needs a routable address. So the simplest solution is to run in host mode, so ES obtains the ip address of the host.

What are you trying to achieve?

**Comment by rsingh2411** [comment]
Thanks for the reply. We are using Elastic search container and its discovery is done via HA Proxy and  consul. HA Proxy front end port is bind to 9200 and backend to host on which elastic search containe ris running. As mentioned container run in Host mode, there was a conflict. However we have excluded 9200 9300 ports from Mesos offers so the issue is not reroducible now.

**Comment by philwinder** [comment]
Understood, thanks. Yes, you shouldn't give ports to Mesos that are in use on your system.
