### ISSUE TITLE
Add hostname flag

### ISSUE THREAD

**Issue by LLParse** [mesos/elasticsearch#561]
Hi @philwinder, this looks to be a great scheduler, but I am unable to use it.

I need to specify a custom hostname for service discovery purposes.

The scheduler either advertises the local hostname, or if you use `--useIpAddress` flag the local IP address. This doesn't work for my use case, because the local hostname/ip is not resolvable by other components and is not something I can control.

This pattern is everywhere, maybe you would consider a pull request?

**Marathon**
--hostname (Optional. Default: hostname of machine): The advertised hostname that is used for the communication with the mesos master. The value is also stored in the persistent store so another standby host can redirect to the elected leader. Note: Default is determined by InetAddress.getLocalHost.

**Chronos**
 -h, --hostname  <arg>                           The advertised hostname stored
                                                  in ZooKeeper so another standby
                                                  host can redirect to this
                                                  elected leader and also sent to
                                                  the Mesos Master
                                                  (default = Gastons-MacBook-Pro.local

**Aurora**
-hostname
	The hostname to advertise in ZooKeeper instead of the locally-resolved hostname.

This list goes on, I think there are more schedulers that support this than not, although I could be wrong! Thank you for your consideration.

**Comment by philwinder** [comment]
Apologies, I thought you just wanted ip address resolution.

Of course we would accept a PR! :-)

I'll add it to the backlog, although I can't guarantee when I will do it.

**Comment by LLParse** [comment]
Excellent :-) I will PR the flag when I get a chance, thanks!

**Comment by philwinder** [comment]
#563
