### ISSUE TITLE
It is not possible to set ES executor Docker image when installed via DC/OS web UI

### ISSUE THREAD

**Issue by dragoslav** [mesos/elasticsearch#562]
By default: [brndnmtthws/elasticsearch-executor:0.7.0](https://raw.githubusercontent.com/mesosphere/universe/version-2.x/repo/packages/E/elasticsearch/0/resource.json) and it's not possible to override it.
Work around for instance is to send directly request to Marathon with `--elasticsearchDockerImage` set ([docs](http://mesos-elasticsearch.readthedocs.org/en/latest/)), but it would be better to have that option in the UI as well.

**Comment by philwinder** [comment]
DCOS is using an old version. 0.7.0 is about six months old. You can override the ES image in 1.0+

**Comment by dragoslav** [comment]
Ok, but who is updating then? I thought it should be a maintainer of the project - that's why I came to you.
I can create a PR for https://github.com/mesosphere/universe if that's the preferred way.

**Comment by philwinder** [comment]
Nobody is responsible for updating, that's Mesosphere's repository for their product.

No, I'm not updating right now. We tried many times in the past and 1) spent too much time doing it and 2) had problems and delays getting it accepted.

Yes, please feel free to raise a PR with them. That would be greatly appreciated.
