### ISSUE TITLE
Version upgrade for elasticsearch?

### ISSUE THREAD

**Issue by sudhaker** [mesos/elasticsearch#567]
Team - do we have any plan to move on to a newer version?

Universe has v 0.7.0; which is a very old and unsupported version.

Ref:
 
https://en.wikipedia.org/wiki/Elasticsearch

https://github.com/mesosphere/universe/blob/version-2.x/repo/packages/E/elasticsearch/0/package.json
https://github.com/mesosphere/universe/blob/version-2.x/repo/packages/E/elasticsearch/0/resource.json

**Comment by thebennos** [comment]
+1 for an version update to stabe version 1.7.4

**Comment by philwinder** [comment]
@sudhaker: Feel free to make a PR to update the DCOS installer. This project is no longer sponsored, so we'll only provide bugfixes and PR requests.

Also, note that the DCOS version is in no way related to the ES version. The ES version is specified by the setting `elasticsearchDockerImage`.

@thebennos: I don't know what version you refer to. If you're refering to ES, 1.7.4 is very out of date. But if you want, you can easily override the ES image. Please see the documentation.

**Comment by thebennos** [comment]
@philwinder 
sorry realized later that already version 2.2 is used. 
After my first look, I had in mind that version 0.7 is used. 

with elasticsearchDockerImage
an own updated image with plugins can be used, so we can close this issue.

**Comment by philwinder** [comment]
Thanks @thebennos .
