### ISSUE TITLE
"Constraints" for the es-executor

### ISSUE THREAD

**Issue by jstabenow** [mesos/elasticsearch#568]
It would be cool for the executors to use [constraints](https://mesosphere.github.io/marathon/docs/constraints.html). E.g.:
- `"rack_id", "CLUSTER", "rack-1"`
- `"storage", "CLUSTER", "r6_ssd`

**Comment by fmarchand** [comment]
Nothing new about constraints for executors ?

**Comment by zemmet** [comment]
+1 
We'd need it to run executors on nodes with non-ephemeral disks to support rexray

**Comment by MarcinMilewski** [comment]
+ 1

**Comment by julienlau** [comment]
+1
