### ISSUE TITLE
mesos/elasticsearch-scheduler Dockerfile

### ISSUE THREAD

**Issue by cookandy** [mesos/elasticsearch#586]
Hi,

Is it possible to get the Dockerfile for `mesos/elasticsearch-scheduler`?  I'd like to build a version of the Docker image with PR https://github.com/mesos/elasticsearch/pull/545 so we can use secluding constraints.

**Comment by rsingh2411** [comment]
Docker file is present in scheduler folder, if you need base image then it isn in https://github.com/mesos/elasticsearch/blob/master/commons/Dockerfile

**Comment by cookandy** [comment]
thanks @rsingh2411
