### ISSUE TITLE
Minuteman not able to parse ElasticSearch executor tasks

### ISSUE THREAD

**Issue by jrx** [mesos/elasticsearch#595]
Hi!

While testing the ElasticSearch framework on DC/OS. I encountered an issue with Minuteman. VIPs are not used by this framework but still Minuteman will fail while parsing the tasks:

```
minuteman-env[5274]: 15:47:59.123 [error] Failed to parse task: {function_clause,[{mesos_state_client,protocol,[<<"TCP">>],
```

I looked into the Mesos `state.json` and found:

```
          "discovery": {
            "visibility": "EXTERNAL",
            "name": "elasticsearch-executor",
            "ports": {
              "ports": [
                {
                  "number": 1025,
                  "name": "CLIENT_PORT",
                  "protocol": "TCP"
                },
                {
                  "number": 1026,
                  "name": "TRANSPORT_PORT",
                  "protocol": "TCP"
                }
              ]
            }
          },
```

Seems like simply converting `TCP` to lowercase `tcp` for the protocol used by the executors will fix this issue.

Regards,
Jan

**Comment by brndnmtthws** [comment]
Perhaps Minuteman should also downcase the string?

**Comment by jrx** [comment]
Yes, I agree.

**Comment by frankscholten** [comment]
Thanks guys! Fixed by https://github.com/mesos/elasticsearch/pull/596
