### ISSUE TITLE
Add shared folder to Vagrantfile to cache gradlew

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#63]

**Comment by jrslv** [comment]
The `.grandle` directory is mounted into `/vagrant` and used in consecutive builds. I think this issue can be closed.

**Comment by frankscholten** [comment]
.gradle was not picked up so I added a synched folder https://github.com/mesos/elasticsearch/commit/439ebfcc435f4fc27a8eccf9daec7932532f7180
