### ISSUE TITLE
Improve management of port metadata in MesosStateServiceRest

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#67]
Use a more elegant way to parse port ranges and reduce code complexity.

**Comment by lguminski** [comment]
currently ports are parsed from this structure
```son
   "slaves":[  
      {  
         "attributes":{  

         },
         "hostname":"slave1",
         "id":"20150604-095931-100667820-5050-1-S2",
         "pid":"slave(1)@172.17.0.9:5051",
         "registered_time":1433411977.23016,
         "reregistered_time":1433412570.01973,
         "resources":{  
            "cpus":4,
            "disk":43017,
            "mem":1004,
            "ports":"[9200-9200, 9300-9300]"
         }
      }
   ]
```
which has the same string describing port as it was in the offer. If I understand correctly, it does not be this way.
* offer can be `"ports":"[9200-9299, 9300-9399]"`
* ports used could could be 9276 and 9325

what do you think on changing the `state.json` to be (service-oriented and not slave-oriented) i.e
to have structure like this (pseudocode):
```json
services: {
  "client":[
    {   
       "hostname": "slave1",
       "port": 9200
    },  
    {   
       "hostname": "slave1",
       "port": 9203
    },  
    {   
       "hostname": "slave1",
       "port": 9207
    },  
  ],  
  "transport service":[
    {   
       "hostname": "slave1",
       "port": 9311
    },  
    {   
       "hostname": "slave1",
       "port": 9302
    },  
    {   
       "hostname": "slave1",
       "port": 9307
    },  
  ]
} 
```
?

**Comment by frankscholten** [comment]
We don't have control over the state.json file because it is generated by the Mesos master.

**Comment by lguminski** [comment]
I think there is a way. Have a look at (closed) https://issues.apache.org/jira/browse/MESOS-2208
> These are the Mesos changes needed to accommodate service discovery information for tasks (see [MESOS-2150](https://issues.apache.org/jira/browse/MESOS-2150)).
> If the frameworks launch task with service discovery info, it is made available through the master state.json endpoint.

https://issues.apache.org/jira/browse/MESOS-2150 task is resolved, so it seems to be possible to declare extra data by tasks

Here seems to be more information how it works https://docs.google.com/document/d/1tpnjfHsa5Joka23CqgGppqnK0jODcElBvTFUBBO-A38/edit#

**Comment by lguminski** [comment]
It seems it is implemented (https://reviews.apache.org/r/29473/diff/#)
```
  // Service discovery information for the task. It is not interpreted
  // or acted upon by Mesos. It is up to a service discovery system
  // to use this information as needed and to handle tasks without
  // service discovery information.
  optional DiscoveryInfo discovery = 12;
```
and then 
```
  if (task.has_discovery()) {
      t.mutable_discovery()->MergeFrom(task.discovery());
  }
```

**Comment by lguminski** [comment]
_DiscoveryInfo_ is less flexible than I thought, but it supports all that is needed:
> The ports field allows the framework to identify the ports a task listens to and explicitly name the functionality they represent and the layer-4 protocol they use (TCP, UDP, or other). For example, a Cassandra task will define ports like “7000,Cluster,TCP”, “7001,SSL,TCP”, “9160,Thrift,TCP”, “9042,Native,TCP”, and “7199,JMX,TCP”. It is up to the service discovery system to use these names and protocol in appropriate ways, potentially combining them with the name field in DiscoveryInfo.
http://mesos.apache.org/documentation/latest/app-framework-development-guide/

**Comment by frankscholten** [comment]
Yes, let's add DiscoveryInfo to the task.

**Comment by philwinder** [comment]
Fixed as of ae45a336e07ee4be6194e7eb653a01274b154cc1
Now using a DiscoveryInfo packet, but still parsing from the state.json.

**Comment by lguminski** [comment]
@philwinder I cannot find in the commit any DiscoveryInfo added to TaskInfo. Could you please navigate me to it?

**Comment by philwinder** [comment]
@lguminski Specifically, in this commit: 566aee59a6288d873a7b5e60c03ab22b2c2804a5
However, I broke a load of Franks tests in the process. So It isn't working as of that commit.
If you want the code, look at the ElasticsearchScheduler.java for the setter, and MesosStateServiceRest.java for the parser.
