### ISSUE TITLE
Create gradle task for pushing images to Docker hub

### ISSUE THREAD

**Issue by mwl** [mesos/elasticsearch#7]

**Comment by frankscholten** [comment]
Current Docker setup requires a volume. Let's see if we can create a build where Dockerfile sits in the root of the module and ADDs the Maven artifact in the package phase.

**Comment by mrmrcoleman** [comment]
Switched elasticsearch-cloud-mesos to use [gradle-docker-plugin from bmuschko](https://github.com/bmuschko/gradle-docker-plugin)

**Comment by mwl** [comment]
Docker isn't being used as part of our release process anymore.
