### ISSUE TITLE
Use an executor in slave docker image.

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#77]
Currently the ES plugin communicates directly with mesos. It should communicate via the executor.

**Comment by frankscholten** [comment]
https://github.com/mesos/elasticsearch/pull/100

**Comment by frankscholten** [comment]
Turned out executor did not run in Docker but it used the command.

**Comment by frankscholten** [comment]
Fixed by https://github.com/mesos/elasticsearch/pull/117
