### ISSUE TITLE
Support deploying multiple Elasticsearch clusters to single Mesos cluster

### ISSUE THREAD

**Issue by keithchambers** [mesos/elasticsearch#91]

**Comment by mwl** [comment]
Task is allocated to @jhftrifork

**Comment by jhftrifork** [comment]
First thing, I'll test it to find out if/why this doesn't work already. Probably something to do with framework names and/or framework ids.

**Comment by frankscholten** [comment]
For this to work the clustername needs to be configurable. Currently the clustername is 'elasticsearch'

**Comment by philwinder** [comment]
Depends on configuration epic. See https://github.com/mesos/elasticsearch/labels/configuration

**Comment by philwinder** [comment]
Duplicate of #111

**Comment by philwinder** [comment]
Fixed in #235
